version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_USER=demo-app
        - APP_UUID=1020
    image: local/demo-app:v11
    environment:
      - SECURE_PASSWORD_1=i-am-encoded-secret-1
      - SECURE_PASSWORD_2=i-am-encoded-secret-2
    restart: always
    networks:
      - demo-app
    ports:
      - "80:8080"
    # depends_on:
    #   - db
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "curl", "-kv", "http://localhost/health/readiness"]
      start_period: 5s
      interval: 15s
      timeout: 5s
      retries: 5

  # db:
  #   image: postgres:alpine3.16
  #   environment:
  #     - POSTGRES_DB=demo-app
  #     - POSTGRES_USER=tool
  #     - POSTGRES_PASSWORD=iamsupersecret
  #   restart: always
  #   networks:
  #     - demo-app
  #   ports:
  #     - "5432"
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "5m"
  #       max-file: "5"

networks:
  demo-app:
    driver: bridge
