apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.namespace }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
  annotations:
    {{- include "demo-app.annotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "demo-app.selectorLabels" . | nindent 6 }}
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  strategy:
    type: {{ .Values.deployment.strategyType }}
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.rollingUpdateMaxUnavailable }}
      maxSurge: {{ .Values.deployment.rollingUpdateMaxSurge }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "demo-app.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.namespace }}-sa
      securityContext:
        fsGroup: {{ .Values.deployment.securityContext.fsGroup }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      topologySpreadConstraints:
      - maxSkew: {{ .Values.deployment.topologySpreadConstraints.maxSkew }}
        topologyKey: {{ .Values.deployment.topologySpreadConstraints.topologyKey }}
        whenUnsatisfiable: {{ .Values.deployment.topologySpreadConstraints.whenUnsatisfiable }}
        labelSelector:
          matchLabels:
            {{- include "demo-app.selectorLabels" . | nindent 14 }}
      {{- if or .Values.app.secrets.manager.enabled .Values.app.secrets.ssm.enabled}}
      volumes:
      - name: "{{ .Values.namespace }}-{{ .Values.app.framework }}-aws-secrets-store"
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "{{ .Values.namespace }}-{{ .Values.app.framework }}-spc"
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.containers.securityContext.allowPrivilegeEscalation }}
            privileged: {{ .Values.containers.securityContext.privileged }}
            readOnlyRootFilesystem: {{ .Values.containers.securityContext.readOnlyRootFilesystem }}
            runAsGroup: {{ .Values.containers.securityContext.runAsGroup }}
            runAsNonRoot: {{ .Values.containers.securityContext.runAsNonRoot }}
            runAsUser: {{ .Values.containers.securityContext.runAsUser }}
          {{- if or .Values.app.secrets.manager.enabled .Values.app.secrets.ssm.enabled}}
          volumeMounts:
          - name: "{{ .Values.namespace }}-{{ .Values.app.framework }}-aws-secrets-store"
            mountPath: /mnt/secrets
            readOnly: true
          {{- end }}
          env:
          {{- if .Values.app.secrets.manager.enabled }}
          {{- range .Values.app.secrets.manager.params }}
          - name: SECRET_{{ upper . }}
            valueFrom:
              secretKeyRef:
                name: "{{ $.Values.namespace }}-{{ $.Values.app.framework }}-aws-secrets"
                key: secret_{{ . }}
          {{- end }}
          {{- end }}
          {{- if .Values.app.secrets.ssm.enabled }}
          {{- range .Values.app.secrets.ssm.params }}
          - name: SSM_{{ upper .}}
            valueFrom:
              secretKeyRef:
                name: "{{ $.Values.namespace }}-{{ $.Values.app.framework }}-aws-secrets"
                key: ssm_{{ . }}
          {{- end }}
          {{- end }}
          - name: IMAGE_ID
            value: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          ports:
            - name: {{ .Values.containers.ports.name }}
              containerPort: {{ .Values.containers.ports.containerPort }}
              protocol: {{ .Values.containers.ports.protocol }}
          resources:
            {{- toYaml .Values.containers.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
              scheme: {{ .Values.readinessProbe.scheme }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
              scheme: {{ .Values.livenessProbe.scheme }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
