apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
  annotations:
    {{- include "demo-app.annotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "demo-app.selectorLabels" . | nindent 6 }}
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  strategy:
    type: {{ .Values.deployment.strategyType }}
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.rollingUpdateMaxUnavailable }}
      maxSurge: {{ .Values.deployment.rollingUpdateMaxSurge }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "demo-app.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      securityContext:
        fsGroup: {{ .Values.deployment.securityContext.fsGroup }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      topologySpreadConstraints:
      - maxSkew: {{ .Values.deployment.topologySpreadConstraints.maxSkew }}
        topologyKey: {{ .Values.deployment.topologySpreadConstraints.topologyKey }}
        whenUnsatisfiable: {{ .Values.deployment.topologySpreadConstraints.whenUnsatisfiable }}
        labelSelector:
          matchLabels:
            {{- include "demo-app.selectorLabels" . | nindent 14 }}
      volumes:
      - name: {{ .Release.Name }}-aws-secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: aws-secrets
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.containers.securityContext.allowPrivilegeEscalation }}
            privileged: {{ .Values.containers.securityContext.privileged }}
            readOnlyRootFilesystem: {{ .Values.containers.securityContext.readOnlyRootFilesystem }}
            runAsGroup: {{ .Values.containers.securityContext.runAsGroup }}
            runAsNonRoot: {{ .Values.containers.securityContext.runAsNonRoot }}
            runAsUser: {{ .Values.containers.securityContext.runAsUser }}
          volumeMounts:
          - name: {{ .Release.Name }}-aws-secrets-store
            mountPath: /mnt/secrets
            readOnly: true
          env:
          - name: SECRET_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-aws-secrets
                key: db_user
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-aws-secrets
                key: db_password
          - name: SECRET_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-aws-secrets
                key: db_host
          - name: SECRET_DBNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-aws-secrets
                key: db_name
          - name: SSM_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-aws-secrets
                key: ssm_name
          - name: SSM_ENVIRONMENT
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-aws-secrets
                key: ssm_environment
          - name: SSM_FRAMEWORK
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-aws-secrets
                key: ssm_framework
          - name: SSM_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-aws-secrets
                key: ssm_api_key
          - name: SSM_HASH_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-aws-secrets
                key: ssm_hash_key
          ports:
            - name: {{ .Values.containers.ports.name }}
              containerPort: {{ .Values.containers.ports.containerPort }}
              protocol: {{ .Values.containers.ports.protocol }}
          resources:
            {{- toYaml .Values.containers.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
              scheme: {{ .Values.readinessProbe.scheme }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
              scheme: {{ .Values.livenessProbe.scheme }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
