apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.namespace }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
  annotations:
    {{- include "demo-app.annotations" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.namespace }}
