{{- if .Values.app.secrets.manager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Release.Name }}-{{ .Values.app.name }}-{{ .Values.app.framework }}-spc"
  namespace: {{ .Values.namespace }}
spec:
  provider: {{ .Values.app.secrets.manager.type }}
  parameters:
    objects: |
      {{- if .Values.app.secrets.ssm.enabled }}
      - objectName: "{{ .Values.app.project }}/{{ .Values.app.environment }}/{{ .Values.app.name }}/{{ .Values.app.framework }}/{{ .Values.app.secrets.manager.name }}-{{ .Values.app.secrets.manager.version }}"
        objectType: "secretsmanager"
        jmesPath:
        {{- range .Values.app.secrets.manager.params }}
          - path: {{ . }}
            objectAlias: secret_{{ . }}
        {{- end }}
      {{- end }}
      {{- if .Values.app.secrets.ssm.enabled }}
      {{- range .Values.app.secrets.ssm.params }}
      - objectName: "/{{ $.Values.app.project }}/{{ $.Values.app.environment }}/{{ $.Values.app.name }}/{{ $.Values.app.framework }}/{{ . }}"
        objectType: "ssmparameter"
        objectAlias: ssm_{{ . }}
      {{- end }}
      {{- end }}
  secretObjects:
    - secretName: "{{ .Release.Name }}-{{ .Values.app.name }}-{{ .Values.app.framework }}-aws-secrets"
      type: Opaque
      data:
        {{- if .Values.app.secrets.manager.enabled }}
        {{- range .Values.app.secrets.manager.params }}
        - objectName: secret_{{ . }}
          key: secret_{{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.app.secrets.ssm.enabled }}
        {{- range .Values.app.secrets.ssm.params }}
        - objectName: ssm_{{ . }}
          key: ssm_{{ . }}
        {{- end }}
        {{- end }}
{{- end}}
