{{- /*
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.namespace }}-secrets
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
  annotations:
    {{- include "demo-app.annotations" . | nindent 4 }}
type: Opaque
data:
  SECRET_USER: aS1hbS1lbmNvZGVkLXNlY3JldC0xCg==
  SECRET_PASSWORD: aS1hbS1lbmNvZGVkLXNlY3JldC0yCg==
  SECRET_HOST: aS1hbS1lbmNvZGVkLXNlY3JldC0xCg==
  SECRET_DBHOST: aS1hbS1lbmNvZGVkLXNlY3JldC0xCg==
  SSM_NAME: aS1hbS1lbmNvZGVkLXNlY3JldC0xCg==
  SSM_ENVIRONMENT: aS1hbS1lbmNvZGVkLXNlY3JldC0xCg==
  SSM_FRAMEWORK: aS1hbS1lbmNvZGVkLXNlY3JldC0xCg==
  SSM_API_KEY: aS1hbS1lbmNvZGVkLXNlY3JldC0xCg==
  SSH_HASH_KEY: aS1hbS1lbmNvZGVkLXNlY3JldC0xCg==
*/ -}}
