{{- if .Values.app.secrets.manager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: {{ .Values.namespace }}
spec:
  provider: {{ .Values.app.secrets.manager.type }}
  parameters:
    objects: |
      - objectName: "{{ .Values.app.project }}/{{ .Values.app.environment }}/{{ .Values.app.framework }}/{{ .Values.app.secrets.manager.name }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: user
            objectAlias: db_user
          - path: password
            objectAlias: db_password
          - path: host
            objectAlias: db_host
          - path: dbname
            objectAlias: db_name
      {{- if .Values.app.secrets.ssm.enabled }}
      {{- range .Values.app.secrets.ssm.params }}
      - objectName: "/{{ $.Values.app.project }}/{{ $.Values.app.environment }}/{{ $.Values.app.framework }}/{{ . }}"
        objectType: "ssmparameter"
        objectAlias: ssm_{{ . }}
      {{- end }}
      {{- end }}
  secretObjects:
    - secretName: {{ .Release.Name }}-aws-secrets
      type: Opaque
      data:
        - objectName: db_user
          key: db_user
        - objectName: db_password
          key: db_password
        - objectName: db_host
          key: db_host
        - objectName: db_name
          key: db_name
        {{- if .Values.app.secrets.ssm.enabled }}
        {{- range .Values.app.secrets.ssm.params }}
        - objectName: ssm_{{ . }}
          key: ssm_{{ . }}
        {{- end }}
        {{- end }}
{{- end}}
