{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-sa
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
  annotations:
    {{- include "demo-app.annotations" . | nindent 4 }}
    {{- include "demo-app.serviceAccountAnnotations" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
